/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as boxv2Sol from "./Boxv2.sol";
export type { boxv2Sol };
export type { Box } from "./Box";
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { Box__factory } from "./factories/Box__factory";
export type { BoxV2 } from "./Boxv2.sol/BoxV2";
export { BoxV2__factory } from "./factories/Boxv2.sol/BoxV2__factory";
export { Lock__factory } from "./factories/Lock__factory";
