/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Box } from "./Box";
export type { BoxV2 } from "./BoxV2";
export * as factories from "./factories";
export { Box__factory } from "./factories/Box__factory";
export { BoxV2__factory } from "./factories/BoxV2__factory";
