/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as boxv2Sol from "./Boxv2.sol";
export { Box__factory } from "./Box__factory";
export { Lock__factory } from "./Lock__factory";
